// Generated by Skyramp v1.3.35 on 2026-07-22 16:29:38.30274922 +0000 UTC m=+360.971202679
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboard-new-button-tooltip.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_new_button_tooltip_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { LoginPage } from '../../pages/generalPages/loginPage.js';
import { DashboardsFormValidationPage } from '../../pages/dashboardPages/dashboardsFormValidationPage.js';

const pageTimeout = 15000;

// Test data
const dashboardsUrl = "http://localhost:5080/web/dashboards?org_identifier=default";
const newDashboardTooltip = "Create a new dashboard in this folder";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(607000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    /*----- Page objects -----*/
    const loginPage = new LoginPage(skyrampPage);
    const dashboardsFormValidationPage = new DashboardsFormValidationPage(skyrampPage);

    /*----- Login -----*/
    await loginPage.gotoLoginPage();
    await loginPage.login();
    await skyrampPage.waitForSelector("text=Home");

    /*----- Navigate to Dashboards list -----*/
    await skyrampPage.goto(dashboardsUrl);
    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(5000);

    /*----- Verify tooltip and button still functions -----*/
    await expect(skyrampPage.locator('[data-test="dashboard-new"]')).toHaveAttribute('title', newDashboardTooltip);

    await dashboardsFormValidationPage.openAddDashboardForm();
    await expect(dashboardsFormValidationPage.getDashboardDialogLocator()).toBeVisible();

    await dashboardsFormValidationPage.cancelDashboardForm();
    await expect(dashboardsFormValidationPage.getDashboardDialogLocator()).not.toBeVisible();
});
