// Generated by Skyramp v1.3.35 on 2026-07-23 14:32:40.697033244 +0000 UTC m=+596.593931679
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output date-time-picker-tooltip-and-relative-range-select.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/date_time_picker_tooltip_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../pages/page-manager.js';

const pageTimeout = 15000;

// Test data
const BASE_URL = 'http://localhost:5080';
const DATE_TIME_TOOLTIP_TEXT = 'Select a relative or absolute time range';

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(999000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pm = new PageManager(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // Log in as the root user (POM handles URL, retries, and post-login wait)
    await pm.loginPage.gotoLoginPage();
    await pm.loginPage.loginAsInternalUser();
    await pm.loginPage.login();

    await page.goto(`${BASE_URL}/web/logs?org_identifier=default`);

    // Hover the date-time-picker trigger button to surface its tooltip, then
    // assert the `title` attribute added to it in this PR (web/src/components/DateTime.vue).
    await pm.logsPage.getDateTimeButton().hover();
    await expect(pm.logsPage.getDateTimeButton()).toHaveAttribute('title', DATE_TIME_TOOLTIP_TEXT);

    // Open the date-time picker and select the "Past 30 Minutes" relative range.
    await pm.logsVisualise.setRelative("30", "m");

    // Assert the button's visible label updates to reflect the selected relative range.
    await expect(pm.logsPage.getDateTimeButton()).toContainText('Past 30 Minutes');

    await page.keyboard.press("Escape");
    await pm.logsPage.clickLogsToggle();

    expect(errors).toHaveLength(0);
});
